public class BlowfishTest {
	public static void main(String[] args) {

		// 实际应用中这里应是个随机数
		String keyString = "hello cnjbb!";
		String testString = "独孤求胜--over~~~Reached? Yes! random number generated by the rand-machine";
		System.out
				.println("加密前**************\n" + "testString = " + testString);
		Blowfish crypt = new Blowfish(keyString);
		System.out.println("开始加密");
		testString = crypt.encryptString(testString);
		System.out.println("加密之后**************\n" + "testString = "
				+ testString);
		System.out.println("开始解密");
		testString = crypt.decryptString(testString);
		System.out.println("解密之后**************\n" + "testString = "
				+ testString);
	}
}